version: '3'
services:
    graph-api:
        build: .
        depends_on:
            - mongo
        links:
            - mongo
        environment:
            NODE_ENV: development
            MONGO_URL: mongodb://mongo/database
        ports:
            - "5000:5000"
        volumes:
            - "./src:/app/src"
            - "./dist:/app/dist"
            - "./package.json:/app/package.json"
        entrypoint: "npm run watch"

    mongo:
        image: mongo
